/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PCR;

/**
 *
 * @author stas
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel(int CellNumb, String data) {
        String str = ", ";
        int dif = 5 - Integer.toString(CellNumb).length() - data.length();
        
        
        for(int i = 0; i < dif; i++){           
            str = str + " ";
        }
        initComponents();
        jcbData.setText(Integer.toString(CellNumb) + str + data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jcbData = new javax.swing.JCheckBox();
        jlFAMColor = new javax.swing.JLabel();
        jcbFAM = new javax.swing.JCheckBox();
        jlHEXColor = new javax.swing.JLabel();
        jcbHEX = new javax.swing.JCheckBox();
        jlRDXColor = new javax.swing.JLabel();
        jcbRDX = new javax.swing.JCheckBox();
        jlCY5 = new javax.swing.JLabel();
        jcbCY5 = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(355, 26));
        setMinimumSize(new java.awt.Dimension(355, 26));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jcbData.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jcbData.setText("00, 000");
        add(jcbData);

        jlFAMColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PCR/blue.jpg"))); // NOI18N
        add(jlFAMColor);

        jcbFAM.setText("FAM");
        jcbFAM.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(jcbFAM);

        jlHEXColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PCR/green.jpg"))); // NOI18N
        add(jlHEXColor);

        jcbHEX.setText("HEX");
        jcbHEX.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(jcbHEX);

        jlRDXColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PCR/yellow.jpg"))); // NOI18N
        add(jlRDXColor);

        jcbRDX.setText("RDX");
        jcbRDX.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(jcbRDX);

        jlCY5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PCR/red.jpg"))); // NOI18N
        add(jlCY5);

        jcbCY5.setText("CY5");
        jcbCY5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(jcbCY5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jcbCY5;
    private javax.swing.JCheckBox jcbData;
    private javax.swing.JCheckBox jcbFAM;
    private javax.swing.JCheckBox jcbHEX;
    private javax.swing.JCheckBox jcbRDX;
    private javax.swing.JLabel jlCY5;
    private javax.swing.JLabel jlFAMColor;
    private javax.swing.JLabel jlHEXColor;
    private javax.swing.JLabel jlRDXColor;
    // End of variables declaration//GEN-END:variables
}
